# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TXL Industries
email: GunjalTXL@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Buisness website for TXL industries
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gunjaltxl.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: TXL Industry
address_line: India, Aurangabad
telephone_number: +91 83800 46971
fax_number: 
company_email: GunjalTXL@gmail.com
google_map: https://maps.app.goo.gl/gEezA9tpVqVmyVNv8

# Social Link
facebook_link: 
twitter_link: 
linkedin_link: 
googleplus_link: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
